# Generated by Django 4.2.4 on 2023-08-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="updated_at",
            new_name="Updated_at",
        ),
    ]
